<?php

namespace App\Domains\Update\Database\Seeders;

use App\Domains\Project\Entities\Project;
use App\Domains\Update\Entities\Update;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class UpdateSeeder extends Seeder
{
    public function run(): void
    {
        $projects = Project::all();

        $updates = [
            // E-commerce Platform (Project ID: 1) - Cliente Acme Corp (ID: 1)
            [
                'project_id' => 1,
                'customer_id' => 1, // Acme Corp
                'title' => 'Nova funcionalidade de carrinho de compras',
                'caption' => 'Implementação do carrinho persistente',
                'description' => 'Adicionada funcionalidade de carrinho de compras que persiste entre sessões. Incluí validação de estoque em tempo real e cálculo automático de frete.',
                'views' => 15,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 1,
                'customer_id' => 2, // TechStart Solutions
                'title' => 'Correção de bugs no sistema de pagamento',
                'caption' => 'Fixes críticos no checkout',
                'description' => 'Corrigidos problemas relacionados ao processamento de pagamentos via cartão de crédito. Melhorada a integração com gateway de pagamento.',
                'views' => 8,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            
            // CRM System (Project ID: 2)
            [
                'project_id' => 2,
                'customer_id' => 1, // Acme Corp
                'title' => 'Dashboard de vendas atualizado',
                'caption' => 'Novos gráficos e métricas',
                'description' => 'Implementado novo dashboard com gráficos interativos, métricas de conversão e relatórios de performance de vendas.',
                'views' => 22,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2,
                'customer_id' => 1, // Acme Corp
                'title' => 'Integração com WhatsApp Business',
                'caption' => 'Comunicação direta com clientes',
                'description' => 'Adicionada integração com WhatsApp Business API para comunicação direta com leads e clientes através da plataforma.',
                'views' => 31,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],

            // Mobile App (Project ID: 3)
            [
                'project_id' => 3,
                'customer_id' => 3, // Global Industries
                'title' => 'Otimização de performance',
                'caption' => 'App 40% mais rápido',
                'description' => 'Implementadas otimizações que resultaram em 40% de melhoria na velocidade de carregamento. Reduzido uso de memória em 25%.',
                'views' => 12,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 3, // Global Industries
                'title' => 'Nova funcionalidade de notificações push',
                'caption' => 'Engajamento melhorado',
                'description' => 'Sistema de notificações push personalizadas baseado no comportamento do usuário. Inclui segmentação avançada.',
                'views' => 7,
                'hash' => Str::uuid()->toString(),
                'status' => 'draft',
            ],

            // Analytics Dashboard (Project ID: 4)
            [
                'project_id' => 4,
                'customer_id' => 4, // Digital Innovations
                'title' => 'Relatórios em tempo real',
                'caption' => 'Dados atualizados instantaneamente',
                'description' => 'Implementado sistema de relatórios em tempo real com WebSockets. Dados são atualizados automaticamente sem necessidade de refresh.',
                'views' => 18,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],

            // API Gateway (Project ID: 6)
            [
                'project_id' => 6,
                'customer_id' => 2, // TechStart Solutions
                'title' => 'Implementação de rate limiting',
                'caption' => 'Proteção contra abuso da API',
                'description' => 'Adicionado sistema de rate limiting por IP e por usuário. Configuração flexível de limites baseados no plano do cliente.',
                'views' => 9,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 3, // Global Industries
                'title' => 'Documentação interativa da API',
                'caption' => 'Swagger UI implementado',
                'description' => 'Criada documentação interativa usando Swagger UI. Desenvolvedores podem testar endpoints diretamente na documentação.',
                'views' => 25,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            
            // Atualizações Globais (aplicam-se a todos os projetos do grupo)
            [
                'project_id' => 1, // E-commerce base
                'customer_id' => null, // NULL = Global para todos os clientes do grupo
                'title' => 'Atualização de Segurança - SSL/TLS',
                'caption' => 'Melhoria global de segurança',
                'description' => 'Implementada nova versão do protocolo SSL/TLS em todos os projetos. Esta atualização melhora significativamente a segurança das comunicações.',
                'views' => 45,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2, // CRM base
                'customer_id' => null, // NULL = Global para todos os clientes do grupo
                'title' => 'Nova política de LGPD',
                'caption' => 'Conformidade legal atualizada',
                'description' => 'Implementadas novas funcionalidades para compliance com LGPD. Inclui controles de consentimento e relatórios de privacidade.',
                'views' => 32,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],

            // Mais atualizações para testar paginação
            [
                'project_id' => 1,
                'customer_id' => 1,
                'title' => 'Sistema de cupons de desconto',
                'caption' => 'Promoções e campanhas de marketing',
                'description' => 'Implementado sistema completo de cupons de desconto com diferentes tipos: percentual, valor fixo e frete grátis.',
                'views' => 28,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 1,
                'customer_id' => 2,
                'title' => 'Integração com marketplaces',
                'caption' => 'Expansão de canais de venda',
                'description' => 'Conectado sistema com principais marketplaces: Mercado Livre, Amazon e Magazine Luiza.',
                'views' => 19,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2,
                'customer_id' => 3,
                'title' => 'Automação de e-mail marketing',
                'caption' => 'Campanhas automáticas',
                'description' => 'Sistema de automação que envia e-mails baseados no comportamento do cliente: abandono de carrinho, aniversário, etc.',
                'views' => 35,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 2,
                'title' => 'Interface redesenhada',
                'caption' => 'Nova experiência do usuário',
                'description' => 'Complete redesign da interface do app com foco na usabilidade e acessibilidade. Seguindo Material Design 3.',
                'views' => 42,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 4,
                'customer_id' => 1,
                'title' => 'Exportação de relatórios em PDF',
                'caption' => 'Relatórios para impressão',
                'description' => 'Adicionada funcionalidade de exportar todos os gráficos e dados em formato PDF profissional.',
                'views' => 16,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 4,
                'title' => 'Cache inteligente',
                'caption' => 'Performance otimizada',
                'description' => 'Implementado sistema de cache inteligente que reduz latência em 60% nas requisições mais frequentes.',
                'views' => 23,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 1,
                'customer_id' => 3,
                'title' => 'Sistema de avaliações',
                'caption' => 'Reviews e ratings de produtos',
                'description' => 'Sistema completo de avaliações com fotos, comentários e sistema de moderação automática.',
                'views' => 31,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2,
                'customer_id' => 1,
                'title' => 'Assistente virtual com IA',
                'caption' => 'Chatbot inteligente',
                'description' => 'Implementado assistente virtual usando IA para atendimento automático 24/7 aos clientes.',
                'views' => 67,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 4,
                'title' => 'Modo offline',
                'caption' => 'Funcionalidade sem internet',
                'description' => 'App agora funciona offline, sincronizando dados automaticamente quando conectividade for restaurada.',
                'views' => 29,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 4,
                'customer_id' => 2,
                'title' => 'Alertas personalizados',
                'caption' => 'Notificações inteligentes',
                'description' => 'Sistema de alertas que monitora métricas importantes e notifica automaticamente quando limites são atingidos.',
                'views' => 18,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 3,
                'title' => 'Versionamento de API',
                'caption' => 'Controle de versões',
                'description' => 'Implementado sistema de versionamento da API mantendo compatibilidade com versões anteriores.',
                'views' => 14,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 1,
                'customer_id' => 4,
                'title' => 'Programa de fidelidade',
                'caption' => 'Pontos e recompensas',
                'description' => 'Sistema completo de programa de fidelidade com pontos, níveis VIP e recompensas exclusivas.',
                'views' => 41,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2,
                'customer_id' => 4,
                'title' => 'Integração com contabilidade',
                'caption' => 'Sincronização fiscal',
                'description' => 'Integração direta com sistemas contábeis para automatizar lançamentos fiscais e controle financeiro.',
                'views' => 22,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 1,
                'title' => 'Reconhecimento biométrico',
                'caption' => 'Login por impressão digital',
                'description' => 'Adicionado suporte para login biométrico usando impressão digital e reconhecimento facial.',
                'views' => 38,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 4,
                'customer_id' => 3,
                'title' => 'Análise preditiva',
                'caption' => 'IA para previsões',
                'description' => 'Machine Learning implementado para análise preditiva de vendas e comportamento de clientes.',
                'views' => 55,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 1,
                'title' => 'Monitoramento avançado',
                'caption' => 'Logs e métricas detalhadas',
                'description' => 'Sistema completo de monitoramento com logs estruturados, métricas de performance e alertas proativos.',
                'views' => 27,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 1,
                'customer_id' => 2,
                'title' => 'Chat de suporte em tempo real',
                'caption' => 'Atendimento instantâneo',
                'description' => 'Widget de chat integrado para suporte em tempo real com transfer para atendentes humanos.',
                'views' => 33,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2,
                'customer_id' => 2,
                'title' => 'Segmentação avançada',
                'caption' => 'Targeting preciso',
                'description' => 'Ferramenta de segmentação de clientes com filtros avançados e criação de audiências personalizadas.',
                'views' => 21,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 3,
                'title' => 'Sincronização entre dispositivos',
                'caption' => 'Dados em tempo real',
                'description' => 'Sincronização automática de dados entre smartphone, tablet e desktop em tempo real.',
                'views' => 26,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 4,
                'customer_id' => 4,
                'title' => 'Dashboard mobile',
                'caption' => 'Gestão pelo celular',
                'description' => 'Versão mobile responsiva do dashboard para acompanhar métricas importantes pelo smartphone.',
                'views' => 39,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 2,
                'title' => 'Autenticação OAuth 2.0',
                'caption' => 'Login social implementado',
                'description' => 'Suporte completo para OAuth 2.0 com login via Google, Facebook, Apple e Microsoft.',
                'views' => 30,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 1,
                'customer_id' => 1,
                'title' => 'Recomendações personalizadas',
                'caption' => 'IA para sugestões',
                'description' => 'Sistema de recomendações baseado em IA que sugere produtos personalizados para cada cliente.',
                'views' => 44,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2,
                'customer_id' => 3,
                'title' => 'Relatórios customizáveis',
                'caption' => 'Reports sob medida',
                'description' => 'Construtor de relatórios que permite criar dashboards personalizados com drag-and-drop.',
                'views' => 17,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 2,
                'title' => 'Tema escuro',
                'caption' => 'Modo noturno',
                'description' => 'Implementado tema escuro para melhor experiência em ambientes com pouca luz.',
                'views' => 52,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 4,
                'customer_id' => 1,
                'title' => 'Comparativo temporal',
                'caption' => 'Análise histórica',
                'description' => 'Ferramenta para comparar métricas entre diferentes períodos com visualizações interativas.',
                'views' => 24,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 4,
                'title' => 'WebHooks configuráveis',
                'caption' => 'Integração flexível',
                'description' => 'Sistema de webhooks que permite integração em tempo real com sistemas externos.',
                'views' => 15,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 1,
                'customer_id' => 3,
                'title' => 'Busca inteligente',
                'caption' => 'Pesquisa com IA',
                'description' => 'Mecanismo de busca inteligente que entende sinônimos e corrige erros ortográficos automaticamente.',
                'views' => 36,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2,
                'customer_id' => 1,
                'title' => 'Pipeline visual de vendas',
                'caption' => 'Kanban de oportunidades',
                'description' => 'Interface visual de pipeline de vendas com drag-and-drop para gerenciar oportunidades.',
                'views' => 40,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 4,
                'title' => 'Controles parentais',
                'caption' => 'Segurança para menores',
                'description' => 'Sistema de controle parental com filtros de conteúdo e limites de tempo de uso.',
                'views' => 20,
                'hash' => Str::uuid()->toString(),
                'status' => 'draft',
            ],
            [
                'project_id' => 4,
                'customer_id' => 2,
                'title' => 'Backup automático',
                'caption' => 'Proteção de dados',
                'description' => 'Sistema de backup automático com versionamento e restauração point-in-time.',
                'views' => 13,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],

            // === ATUALIZAÇÕES ADICIONAIS PARA ATINGIR 20+ POR PROJETO ===

            // E-commerce Platform (ID: 1) - Mais 10 atualizações
            [
                'project_id' => 1,
                'customer_id' => 1,
                'title' => 'Sistema de gestão de estoque avançado',
                'caption' => 'Controle inteligente de inventário',
                'description' => 'Implementado sistema de gestão de estoque com alertas automáticos, previsão de demanda e integração com fornecedores.',
                'views' => 28,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 1,
                'customer_id' => 2,
                'title' => 'Multi-idiomas e multi-moedas',
                'caption' => 'Expansão internacional',
                'description' => 'Suporte completo para múltiplos idiomas e moedas, com conversão automática e localização de conteúdo.',
                'views' => 35,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 1,
                'customer_id' => 1,
                'title' => 'Realidade aumentada para produtos',
                'caption' => 'Experiência imersiva',
                'description' => 'Funcionalidade AR que permite visualizar produtos em 3D no ambiente do cliente antes da compra.',
                'views' => 42,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 1,
                'customer_id' => 2,
                'title' => 'Marketplace interno',
                'caption' => 'Vendedores terceirizados',
                'description' => 'Plataforma para vendedores externos com sistema de comissões, avaliações e gestão de produtos.',
                'views' => 31,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 1,
                'customer_id' => 1,
                'title' => 'Análise de comportamento com IA',
                'caption' => 'Insights de clientes',
                'description' => 'Sistema de análise comportamental que identifica padrões de compra e otimiza a experiência do usuário.',
                'views' => 29,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 1,
                'customer_id' => 2,
                'title' => 'Sistema de assinaturas',
                'caption' => 'Modelo de recorrência',
                'description' => 'Implementação de sistema de assinaturas com cobrança recorrente e gestão de planos flexíveis.',
                'views' => 38,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 1,
                'customer_id' => 1,
                'title' => 'Checkout em uma página',
                'caption' => 'Conversão otimizada',
                'description' => 'Processo de checkout simplificado em uma única página para reduzir abandono de carrinho.',
                'views' => 33,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 1,
                'customer_id' => 2,
                'title' => 'Gestão de devoluções automatizada',
                'caption' => 'Processo de RMA',
                'description' => 'Sistema automatizado para solicitação, aprovação e processamento de devoluções de produtos.',
                'views' => 26,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 1,
                'customer_id' => 1,
                'title' => 'Comparador de produtos',
                'caption' => 'Decisão informada',
                'description' => 'Ferramenta para comparar especificações, preços e avaliações de produtos lado a lado.',
                'views' => 24,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 1,
                'customer_id' => 2,
                'title' => 'Integração com ERP corporativo',
                'caption' => 'Sincronização empresarial',
                'description' => 'Integração completa com sistemas ERP para sincronização de dados financeiros e operacionais.',
                'views' => 19,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],

            // CRM System (ID: 2) - Mais 11 atualizações
            [
                'project_id' => 2,
                'customer_id' => 1,
                'title' => 'Automação de lead scoring',
                'caption' => 'Qualificação inteligente',
                'description' => 'Sistema de pontuação automática de leads baseado em comportamento e características demográficas.',
                'views' => 45,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2,
                'customer_id' => 2,
                'title' => 'Integração com calendários',
                'caption' => 'Agendamento sincronizado',
                'description' => 'Sincronização bidirecional com Google Calendar, Outlook e Apple Calendar para reuniões e follow-ups.',
                'views' => 32,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2,
                'customer_id' => 3,
                'title' => 'Dashboard executivo em tempo real',
                'caption' => 'Métricas ao vivo',
                'description' => 'Dashboard executivo com KPIs atualizados em tempo real e alertas para metas importantes.',
                'views' => 38,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2,
                'customer_id' => 4,
                'title' => 'Geolocalização de clientes',
                'caption' => 'Mapeamento territorial',
                'description' => 'Sistema de geolocalização para mapear clientes por território e otimizar rotas de visitas.',
                'views' => 27,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2,
                'customer_id' => 1,
                'title' => 'Forecasting de vendas com IA',
                'caption' => 'Previsões precisas',
                'description' => 'Algoritmo de machine learning para previsão de vendas baseado em dados históricos e tendências.',
                'views' => 41,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2,
                'customer_id' => 2,
                'title' => 'Sistema de tickets de suporte',
                'caption' => 'Atendimento estruturado',
                'description' => 'Plataforma integrada de tickets para gerenciar solicitações de suporte de clientes.',
                'views' => 34,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2,
                'customer_id' => 3,
                'title' => 'Campanhas de nurturing automatizadas',
                'caption' => 'Jornada do cliente',
                'description' => 'Sequências automatizadas de e-mails e ações baseadas no estágio do lead no funil de vendas.',
                'views' => 29,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2,
                'customer_id' => 4,
                'title' => 'Análise de sentiment em interações',
                'caption' => 'Inteligência emocional',
                'description' => 'Análise automática do sentimento em e-mails e mensagens para identificar satisfação do cliente.',
                'views' => 36,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2,
                'customer_id' => 1,
                'title' => 'Integração com redes sociais',
                'caption' => 'Monitoramento social',
                'description' => 'Integração com Facebook, LinkedIn e Instagram para capturar leads e monitorar menções.',
                'views' => 33,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2,
                'customer_id' => 2,
                'title' => 'Gestão de contratos digitais',
                'caption' => 'Assinatura eletrônica',
                'description' => 'Sistema para criação, envio e assinatura digital de contratos com validade jurídica.',
                'views' => 25,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 2,
                'customer_id' => 3,
                'title' => 'Relatórios de ROI por campanha',
                'caption' => 'Análise de retorno',
                'description' => 'Relatórios detalhados de retorno sobre investimento para cada campanha de marketing.',
                'views' => 31,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],

            // Mobile App (ID: 3) - Mais 12 atualizações
            [
                'project_id' => 3,
                'customer_id' => 1,
                'title' => 'Widgets para tela inicial',
                'caption' => 'Acesso rápido',
                'description' => 'Widgets personalizáveis para tela inicial com informações importantes e ações rápidas.',
                'views' => 44,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 2,
                'title' => 'Suporte a Apple Watch',
                'caption' => 'Experiência wearable',
                'description' => 'App companion para Apple Watch com notificações e funcionalidades essenciais.',
                'views' => 37,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 3,
                'title' => 'Compartilhamento social avançado',
                'caption' => 'Viral marketing',
                'description' => 'Sistema de compartilhamento com templates personalizados e tracking de performance.',
                'views' => 28,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 4,
                'title' => 'Backup e sincronização na nuvem',
                'caption' => 'Dados seguros',
                'description' => 'Backup automático de dados do usuário com sincronização entre dispositivos via cloud.',
                'views' => 33,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 1,
                'title' => 'Sistema de achievements',
                'caption' => 'Gamificação avançada',
                'description' => 'Sistema de conquistas e badges para incentivar engajamento e uso contínuo do app.',
                'views' => 41,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 2,
                'title' => 'Busca por voz',
                'caption' => 'Interface conversacional',
                'description' => 'Funcionalidade de busca e comandos por voz com processamento de linguagem natural.',
                'views' => 39,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 3,
                'title' => 'Modo de acessibilidade avançado',
                'caption' => 'Inclusão digital',
                'description' => 'Recursos de acessibilidade para usuários com deficiências visuais, auditivas e motoras.',
                'views' => 26,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 4,
                'title' => 'Análise de performance do app',
                'caption' => 'Métricas de uso',
                'description' => 'Dashboard com métricas de performance, crashes, tempo de uso e jornadas do usuário.',
                'views' => 35,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 1,
                'title' => 'Integração com assistentes virtuais',
                'caption' => 'Siri e Google Assistant',
                'description' => 'Integração nativa com Siri e Google Assistant para comandos por voz e shortcuts.',
                'views' => 42,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 2,
                'title' => 'Sistema de feedback in-app',
                'caption' => 'Melhoria contínua',
                'description' => 'Ferramenta para coleta de feedback dos usuários com screenshots e categorização.',
                'views' => 30,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 3,
                'title' => 'Suporte a tablets',
                'caption' => 'Interface adaptativa',
                'description' => 'Layout otimizado para tablets com aproveitamento total da tela maior.',
                'views' => 27,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 3,
                'customer_id' => 4,
                'title' => 'Modo de economia de bateria',
                'caption' => 'Eficiência energética',
                'description' => 'Modo especial que reduz consumo de bateria limitando funcionalidades secundárias.',
                'views' => 32,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],

            // Analytics Dashboard (ID: 4) - Mais 13 atualizações
            [
                'project_id' => 4,
                'customer_id' => 1,
                'title' => 'Machine Learning para anomalias',
                'caption' => 'Detecção inteligente',
                'description' => 'Sistema de ML que identifica automaticamente anomalias nos dados e gera alertas.',
                'views' => 47,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 4,
                'customer_id' => 2,
                'title' => 'Dashboards colaborativos',
                'caption' => 'Trabalho em equipe',
                'description' => 'Funcionalidade para criar dashboards colaborativos com comentários e anotações.',
                'views' => 34,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 4,
                'customer_id' => 3,
                'title' => 'Integração com BigQuery',
                'caption' => 'Big Data processing',
                'description' => 'Conectividade nativa com Google BigQuery para análise de grandes volumes de dados.',
                'views' => 29,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 4,
                'customer_id' => 4,
                'title' => 'Visualizações 3D interativas',
                'caption' => 'Gráficos imersivos',
                'description' => 'Gráficos tridimensionais interativos para melhor compreensão de dados complexos.',
                'views' => 41,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 4,
                'customer_id' => 1,
                'title' => 'API para integração externa',
                'caption' => 'Conectividade ampliada',
                'description' => 'API REST completa para integração com sistemas externos e automações.',
                'views' => 33,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 4,
                'customer_id' => 2,
                'title' => 'Relatórios automatizados por email',
                'caption' => 'Entrega programada',
                'description' => 'Sistema de envio automático de relatórios personalizados por email em horários definidos.',
                'views' => 36,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 4,
                'customer_id' => 3,
                'title' => 'Drill-down em tempo real',
                'caption' => 'Análise profunda',
                'description' => 'Capacidade de fazer drill-down em qualquer métrica para análise detalhada em tempo real.',
                'views' => 28,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 4,
                'customer_id' => 4,
                'title' => 'Alertas baseados em ML',
                'caption' => 'Notificações inteligentes',
                'description' => 'Sistema de alertas que usa machine learning para identificar padrões anômalos.',
                'views' => 45,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 4,
                'customer_id' => 1,
                'title' => 'Conectores para SaaS populares',
                'caption' => 'Integração simplificada',
                'description' => 'Conectores pré-configurados para Salesforce, HubSpot, Slack e outras plataformas.',
                'views' => 31,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 4,
                'customer_id' => 2,
                'title' => 'Análise de cohort avançada',
                'caption' => 'Segmentação temporal',
                'description' => 'Ferramenta de análise de cohort para entender comportamento de grupos ao longo do tempo.',
                'views' => 38,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 4,
                'customer_id' => 3,
                'title' => 'Temas customizáveis',
                'caption' => 'Branding personalizado',
                'description' => 'Editor de temas para personalizar cores, fonts e layout conforme identidade da empresa.',
                'views' => 26,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 4,
                'customer_id' => 4,
                'title' => 'Performance monitoring',
                'caption' => 'Otimização contínua',
                'description' => 'Monitoramento de performance de queries e dashboards com sugestões de otimização.',
                'views' => 32,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 4,
                'customer_id' => 1,
                'title' => 'Modo de apresentação',
                'caption' => 'Dashboards executivos',
                'description' => 'Modo especial para apresentações com transições automáticas e foco em KPIs principais.',
                'views' => 29,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],

            // Legacy System Migration (ID: 5) - 20 atualizações (estava zerado)
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Análise de dependências do sistema legado',
                'caption' => 'Mapeamento completo',
                'description' => 'Análise detalhada de todas as dependências e integrações do sistema antigo para planejamento da migração.',
                'views' => 52,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Estratégia de migração de dados',
                'caption' => 'Preservação de informações',
                'description' => 'Plano detalhado para migração segura de dados com validação de integridade e backup completo.',
                'views' => 48,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Ambiente de testes paralelo',
                'caption' => 'Validação segura',
                'description' => 'Configuração de ambiente de testes para validar funcionalidades migradas sem impactar produção.',
                'views' => 31,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Modernização da arquitetura',
                'caption' => 'Stack tecnológico atual',
                'description' => 'Atualização da arquitetura para tecnologias modernas com microserviços e containerização.',
                'views' => 44,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Interface de usuário redesenhada',
                'caption' => 'UX moderna',
                'description' => 'Novo design da interface com foco em usabilidade e experiência do usuário contemporânea.',
                'views' => 37,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Sistema de autenticação moderno',
                'caption' => 'Segurança atualizada',
                'description' => 'Implementação de autenticação moderna com 2FA, SSO e integração com provedores externos.',
                'views' => 39,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'API RESTful completa',
                'caption' => 'Integração moderna',
                'description' => 'Desenvolvimento de API REST moderna para substituir interfaces legadas de integração.',
                'views' => 42,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Migração do banco de dados',
                'caption' => 'Estrutura otimizada',
                'description' => 'Migração e otimização da estrutura do banco de dados para melhor performance e escalabilidade.',
                'views' => 35,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Testes de carga e performance',
                'caption' => 'Validação de capacidade',
                'description' => 'Bateria completa de testes para validar performance e capacidade do novo sistema.',
                'views' => 28,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Documentação técnica atualizada',
                'caption' => 'Knowledge base moderno',
                'description' => 'Criação de documentação técnica completa e atualizada para o novo sistema.',
                'views' => 26,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Treinamento da equipe',
                'caption' => 'Capacitação técnica',
                'description' => 'Programa de treinamento para equipe técnica nas novas tecnologias e processos.',
                'views' => 33,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Plano de rollback',
                'caption' => 'Contingência segura',
                'description' => 'Estratégia detalhada de rollback para reverter à versão anterior em caso de problemas.',
                'views' => 41,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Monitoramento em tempo real',
                'caption' => 'Observabilidade completa',
                'description' => 'Sistema de monitoramento com logs, métricas e alertas para acompanhar a saúde do sistema.',
                'views' => 38,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Otimização de performance',
                'caption' => 'Sistema mais rápido',
                'description' => 'Implementação de otimizações que resultaram em 300% de melhoria na velocidade.',
                'views' => 45,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Backup e disaster recovery',
                'caption' => 'Proteção de dados',
                'description' => 'Sistema robusto de backup e recuperação de desastres para garantir continuidade do negócio.',
                'views' => 29,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Compliance e auditoria',
                'caption' => 'Conformidade regulatória',
                'description' => 'Implementação de controles de compliance e trilhas de auditoria conforme regulamentações.',
                'views' => 34,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Integração com sistemas externos',
                'caption' => 'Conectividade ampliada',
                'description' => 'Reestabelecimento e melhoria das integrações com sistemas externos e parceiros.',
                'views' => 36,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Go-live e suporte pós-migração',
                'caption' => 'Transição suave',
                'description' => 'Execução do go-live com suporte 24/7 durante período crítico pós-migração.',
                'views' => 47,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Relatório de migração final',
                'caption' => 'Documentação de resultados',
                'description' => 'Relatório completo com métricas de sucesso, lições aprendidas e recomendações futuras.',
                'views' => 32,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 5,
                'customer_id' => 1,
                'title' => 'Otimização pós-migração',
                'caption' => 'Melhoria contínua',
                'description' => 'Análise e implementação de melhorias baseadas no uso real após a migração.',
                'views' => 30,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],

            // API Gateway (ID: 6) - Mais 13 atualizações
            [
                'project_id' => 6,
                'customer_id' => 1,
                'title' => 'Load balancing inteligente',
                'caption' => 'Distribuição otimizada',
                'description' => 'Sistema de load balancing que distribui requisições baseado em latência e capacidade dos serviços.',
                'views' => 43,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 2,
                'title' => 'Circuit breaker pattern',
                'caption' => 'Resiliência automática',
                'description' => 'Implementação de circuit breaker para prevenir cascata de falhas entre microserviços.',
                'views' => 37,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 3,
                'title' => 'GraphQL gateway',
                'caption' => 'Consultas flexíveis',
                'description' => 'Suporte a GraphQL para consultas mais eficientes e flexíveis aos microserviços.',
                'views' => 39,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 4,
                'title' => 'Transformação de dados em tempo real',
                'caption' => 'Pipeline de dados',
                'description' => 'Sistema para transformar e enriquecer dados em tempo real durante o trânsito pela API.',
                'views' => 34,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 1,
                'title' => 'Analytics de uso da API',
                'caption' => 'Métricas detalhadas',
                'description' => 'Dashboard com métricas detalhadas de uso, performance e padrões de consumo da API.',
                'views' => 41,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 2,
                'title' => 'Throttling dinâmico',
                'caption' => 'Controle adaptativo',
                'description' => 'Sistema de throttling que se adapta automaticamente baseado na carga dos serviços backend.',
                'views' => 28,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 3,
                'title' => 'Validação de schema automática',
                'caption' => 'Qualidade de dados',
                'description' => 'Validação automática de schemas de entrada e saída para garantir qualidade dos dados.',
                'views' => 32,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 4,
                'title' => 'Mock services para desenvolvimento',
                'caption' => 'Ambiente de dev',
                'description' => 'Serviços mock configuráveis para facilitar desenvolvimento e testes independentes.',
                'views' => 26,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 1,
                'title' => 'Compressão e otimização de payload',
                'caption' => 'Performance de rede',
                'description' => 'Compressão automática e otimização de payloads para reduzir latência e uso de banda.',
                'views' => 35,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 2,
                'title' => 'Blue-green deployment',
                'caption' => 'Deploy sem downtime',
                'description' => 'Sistema de deployment blue-green para atualizações sem interrupção do serviço.',
                'views' => 38,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 3,
                'title' => 'Distributed tracing',
                'caption' => 'Rastreamento completo',
                'description' => 'Sistema de tracing distribuído para rastrear requisições através de todos os microserviços.',
                'views' => 40,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 4,
                'title' => 'Gestão de API keys avançada',
                'caption' => 'Segurança granular',
                'description' => 'Sistema avançado de gestão de API keys com permissões granulares e rotação automática.',
                'views' => 33,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
            [
                'project_id' => 6,
                'customer_id' => 1,
                'title' => 'Alertas e notificações proativas',
                'caption' => 'Monitoramento inteligente',
                'description' => 'Sistema de alertas baseado em ML que detecta problemas antes que afetem os usuários finais.',
                'views' => 42,
                'hash' => Str::uuid()->toString(),
                'status' => 'published',
            ],
        ];

        foreach ($updates as $updateData) {
            // Se não tem customer_id definido, usar o primeiro cliente do projeto
            if (!isset($updateData['customer_id'])) {
                $project = \App\Domains\Project\Entities\Project::find($updateData['project_id']);
                if ($project && $project->customers->isNotEmpty()) {
                    $updateData['customer_id'] = $project->customers->first()->id;
                }
            }
            
            Update::create($updateData);
        }
    }
} 